export const fullServices = [
  // --- MALE SERVICES ---
  { name: "Hair Wash + Hair Cut", price: "150", category: "Hair Cut", type: "Male" },
  { name: "Beard Crafting", price: "100", category: "Beard", type: "Male" },
  { name: "Shave + Beard Trim", price: "100", category: "Beard", type: "Male" },
  { name: "Global Colour (Loreal)", price: "500", category: "Hair Colour", type: "Male" },
  { name: "Global Colour (Garnier)", price: "600", category: "Hair Colour", type: "Male" },
  { name: "Highlight", price: "300", category: "Hair Colour", type: "Male" },
  { name: "Lotus Cleanup", price: "700", category: "Cleanup", type: "Male" },
  { name: "Sehnaz Cleanup", price: "1000", category: "Cleanup", type: "Male" },
  { name: "Lotus Facial", price: "1200", category: "Facial", type: "Male" },
  { name: "O3+ Facial", price: "2500", category: "Facial", type: "Male" },
  { name: "VLCC Facial", price: "1800", category: "Facial", type: "Male" },
  { name: "Head Massage (With Wash)", price: "250", category: "Massage", type: "Male" },
  { name: "Leana Hair Spa", price: "500", category: "Hair Spa", type: "Male" },
  { name: "Keratin (Medium Length)", price: "1500", category: "Treatment", type: "Male" },
  { name: "Straightening (Medium)", price: "1500", category: "Treatment", type: "Male" },

  // --- FEMALE SERVICES ---
  { name: "Stylish Hair Cut", price: "500", category: "Hair Cut", type: "Female" },
  { name: "U-Cut / Deep U-Cut", price: "250", category: "Hair Cut", type: "Female" },
  { name: "Trimming", price: "200", category: "Hair Cut", type: "Female" },
  { name: "Root Touchup (Loreal)", price: "800", category: "Hair Colour", type: "Female" },
  { name: "Global (Shoulder Length)", price: "2500", category: "Hair Colour", type: "Female" },
  { name: "Global (Waist Length)", price: "4000", category: "Hair Colour", type: "Female" },
  { name: "Hair Spa (Loreal)", price: "800", category: "Hair Spa", type: "Female" },
  { name: "Eyebrow", price: "40", category: "Threading", type: "Female" },
  { name: "Upper Lip", price: "40", category: "Threading", type: "Female" },
  { name: "Full Face Threading", price: "150", category: "Threading", type: "Female" },
  { name: "Full Hand Wax", price: "250", category: "Waxing", type: "Female" },
  { name: "Full Leg Wax", price: "350", category: "Waxing", type: "Female" },
  { name: "Full Body Wax", price: "1500", category: "Waxing", type: "Female" },
  { name: "Diamond Facial", price: "1500", category: "Facial", type: "Female" },
  { name: "Gold Facial", price: "1000", category: "Facial", type: "Female" },
  { name: "O3+ Facial", price: "3000", category: "Facial", type: "Female" },
  { name: "Clean Up (Lotus)", price: "700", category: "Cleanup", type: "Female" },
  { name: "Manicure", price: "450", category: "Manicure/Pedicure", type: "Female" },
  { name: "Pedicure", price: "500", category: "Manicure/Pedicure", type: "Female" },
  { name: "Straightening (Waist)", price: "7000", category: "Treatment", type: "Female" },
  { name: "Bridal HD Look", price: "10000", category: "Makeup", type: "Female" },
  { name: "Sider Normal Look", price: "2000", category: "Makeup", type: "Female" },

  // --- KIDS ---
  { name: "Kids Hair Cut", price: "100", category: "Hair Cut", type: "Kids" },
  { name: "Kids Mundan", price: "150", category: "Hair Cut", type: "Kids" },
];

export const fullSlots = [
  { time: "09:00", capacity: 2 },
  { time: "09:30", capacity: 2 },
  { time: "10:00", capacity: 2 },
  { time: "10:30", capacity: 2 },
  { time: "11:00", capacity: 2 },
  { time: "11:30", capacity: 2 },
  { time: "12:00", capacity: 2 },
  { time: "12:30", capacity: 2 },
  { time: "13:00", capacity: 2 },
  { time: "14:00", capacity: 2 },
  { time: "14:30", capacity: 2 },
  { time: "15:00", capacity: 2 },
  { time: "15:30", capacity: 2 },
  { time: "16:00", capacity: 2 },
  { time: "16:30", capacity: 2 },
  { time: "17:00", capacity: 2 },
  { time: "17:30", capacity: 2 },
  { time: "18:00", capacity: 2 },
  { time: "18:30", capacity: 2 },
  { time: "19:00", capacity: 2 },
  { time: "19:30", capacity: 2 },
  { time: "20:00", capacity: 2 },
];